print("Viernes en AIpython")
print("Las maquinas me sorprenden con mucha frecuencia")
print()
print('"23" 23')
print('Una computadora puede ser llamada "inteligente" si logra engañar a una persona haciendole creer que es un humano.')
print("Mateo", "Lavecchia", "19")
print("Mateo", "Lavecchia", "19", sep="_")
print("calle", "numero", "codigo postal", sep="\t")
print("calle", "numero", "codigo postal", sep="\n")
print("Solo podemos ver poco del futuro," "pero lo suficiente para darnos cuenta de que hay mucho que hacer")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

